// Generated by scripts/compile-content.ts — do not edit.
import de_en from "./de-en.json";
import es_en from "./es-en.json";
import fr_en from "./fr-en.json";
import it_en from "./it-en.json";
import ja_en from "./ja-en.json";
import ko_en from "./ko-en.json";
import pt_en from "./pt-en.json";
import zh_en from "./zh-en.json";
import type { Pack } from "../../lib/types";

export const PACKS: Record<string, Pack> = {
  "de-en": de_en as Pack,
  "es-en": es_en as Pack,
  "fr-en": fr_en as Pack,
  "it-en": it_en as Pack,
  "ja-en": ja_en as Pack,
  "ko-en": ko_en as Pack,
  "pt-en": pt_en as Pack,
  "zh-en": zh_en as Pack,
};
